### ISSUE TITLE
Compatibility with NB 12.x

### ISSUE THREAD

**Issue by lmartinpulse** [ArturWisniewski/NB-Thymeleaf-Code-Completion#10]
Hi,

I was unable to install the plugin on latest NB 12.2.  
After validating the license I get this message : 
```
The Plugin Installer found problem timeout of loading Thymeleaf Code Completion[org.netbeans.modules.thymeleafcodecompletion/1.0] while install the following plugins:
Thymeleaf Code Completion
```
Have a nice day

**Comment by kkieffer** [comment]
I had the same issue on NB 12.

**Comment by ArturWisniewski** [comment]
Sorry i was unable to recreate this problem. 
Tested on 12.0 and 12.2 and it is working just fine.
I used clean binary download of NB. 
Please provide error from IDE log, the one provided points to some timeout with no specifics. 
log location: http://wiki.netbeans.org/FaqLogMessagesFile

**Comment by ArturWisniewski** [comment]
No more information provided. Closing.
