### ISSUE TITLE
How to install in Netbeans 8.2?

### ISSUE THREAD

**Issue by andresfranco** [ArturWisniewski/NB-Thymeleaf-Code-Completion#2]
How can i install this plugin?  can you write the installation steps please? thank you.

**Comment by ArturWisniewski** [comment]
Tools -> Plugins -> Downloaded -> Add Plugins -> 
You select org-netbeans-modules-thymeleafcodecompletion.nbm downloaded from releases: 
https://github.com/ArturWisniewski/NB-Thymeleaf-Code-Completion/releases
Hope it helps.
PS To uninstall chose Installed tab instead Downloaded and check Show details.

**Comment by andresfranco** [comment]
Thank you !!
