### ISSUE TITLE
netbeans 9

### ISSUE THREAD

**Issue by marccollin** [ArturWisniewski/NB-Thymeleaf-Code-Completion#4]
any update for netbeans 9?

**Comment by AlexFalappa** [comment]
@marccollin I have successfully installed the plugin on NetBeans 10 voting candidate 5 so I guess there should be no problems in NB 9 as well.

Are you having any specific issue?

**Comment by ArturWisniewski** [comment]
@marccollin New version is released, should be working with Netbeans 8.2, 9.0 and 10.0.
