### ISSUE TITLE
Inline documentation not showing in NB10.0

### ISSUE THREAD

**Issue by icojb25** [ArturWisniewski/NB-Thymeleaf-Code-Completion#9]
I have installed manually the latest release as of today in Netbeans 10.0 but inline documentation does not show

Steps to reproduce:
1) install manually in NB10.0
2) type "th:" and CTRL+space
3) documentation cannot be shown / found for the elements

**Comment by ArturWisniewski** [comment]
I can not reproduce this error. Does anyone else have this problem?

**Comment by ArturWisniewski** [comment]
No response, closing.
